### ISSUE TITLE
Hello Teacher

### ISSUE THREAD

**Issue by XiaoBaiBZS** [jun-csbio/CClass_ZJUT#2]

**Comment by jun-csbio** [comment]
你好！

**Comment by Zyep6** [comment]
额

**Comment by Zyep6** [comment]
![Uploading 1695015491787.jpg…]()

**Comment by Zyep6** [comment]
😂👿👿😓

**Comment by XiaoBaiBZS** [comment]
![IMG_20230917_071710.jpg](https://github.com/jun-csbio/CClass_ZJUT/assets/93860707/04d2de3d-16bc-48cb-aed3-cfe0ca532cd5)
