### ISSUE TITLE
字符型数组输入输出问题

### ISSUE THREAD

**Issue by XiaoBaiBZS** [jun-csbio/CClass_ZJUT#38]
```C
#include<stdio.h>
int main(){
	char a[200];
	int i=0;
	char x;
	//输入 
	do{
		scanf("%c",&x);
		a[i]=x;
		i++;
	}while(getchar()!='\n');//当读入为换行跳出循环 
	//输出 
	for(int k=0;k<i;k++){
		printf("%c",a[k]);
	}
	return 0;
}
```
上述代码旨在循环输入字符到数组a中，直到输入了换行退出，并遍历数组a输出。

> Input：`123456789abcde\n`
> Output：`13579bd\n`

试问数组a为什么没有读入 `2468ace` ？

> 参考CSDN：[C++中getchar（）在循环结构中的运用 原创](https://blog.csdn.net/aimat2020/article/details/119825653)

**Comment by XiaoBaiBZS** [comment]
```C
#include<stdio.h> 
int main(){ 	char a[200]; 	int i=0; 	char x; 	//输入 	do{ 		scanf("%c",&x); 		a[i]=x; 		i++; 	}while(getchar()!='\n');//当读入为换行跳出循环 	//输出 	for(int k=0;k<i;k++){ 		printf("%c",a[k]); 	} 	return 0; }
```

**Comment by XiaoBaiBZS** [comment]
```C
#include<stdio.h>
int main(){
	char a[200];
	int i=0;
	char x;
	//输入 
	do{
		scanf("%c",&x);
		a[i]=x;
		i++;
	}while(x!='\n');//当读入为换行跳出循环 
	//输出 
	for(int k=0;k<i;k++){
		printf("%c",a[k]);
	}
	return 0;
}
```
经过尝试，如果把 ` getchar() ` 换为 `x` 就可以正常输出。

> Input：`123abc\n`
> Output：`123abc\n`

为什么 ` getchar() ` 方法就不可以正常输出呢？

**Comment by Einell** [comment]
#include<stdio.h>  
int main(void){  
    char a[200];  
    int i = 0;  
    char x;  
    // 输入  
    do {  
        x = getchar();  
        if (x != '\n') {  
            a[i] = x;  
            i++;  
        }  
    } while (x != '\n'); // 当读入为换行跳出循环  
    // 输出  
    for (int k = 0; k < i; k++) {  
        printf("%c", a[k]);  
    }  
    return 0;  
}
你这么写试试？

**Comment by Einell** [comment]
#include<stdio.h>
int main(void){
    char a[200];
    int i = 0;
    char x;
    // 输入
    do {
        x = getchar();
        if (x != '\n') {
            a[i] = x;
            i++;
        }
    } while (x != '\n'); // 当读入为换行跳出循环
    // 输出
    for (int k = 0; k < i; k++) {
        printf("%c", a[k]);
    }
    return 0;
}

**Comment by Einell** [comment]
#include<stdio.h>
int main(void){
    char a[200];
    int i = 0;
    char x;
    // 输入
    do {
        x = getchar();
        if (x != '\n') {
            a[i] = x;
            i++;
        }
    } while (x != '\n'); // 当读入为换行跳出循环
    // 输出
    for (int k = 0; k < i; k++) {
        printf("%c", a[k]);
    }
    return 0;
}
你这么写试试？
（为什么我对齐不了）

**Comment by XiaoBaiBZS** [comment]
在GitHub编辑器上使用“```C”字符来划定代码块并采用C语言语法高亮，具体可了解[Markdown 基本语法](https://markdown.com.cn/basic-syntax/)。

**Comment by XiaoBaiBZS** [comment]
> #include<stdio.h> int main(void){ char a[200]; int i = 0; char x; // 输入 do { x = getchar(); if (x != '\n') { a[i] = x; i++; } } while (x != '\n'); // 当读入为换行跳出循环 // 输出 for (int k = 0; k < i; k++) { printf("%c", a[k]); } return 0; } 你这么写试试？ （为什么我对齐不了）

感谢您的回答，您的代码在我的编译器上能正常执行，但是我还是想问我的代码有什么问题。

**Comment by victoryban** [comment]
因为gtechar在判断是否进行下次循环时，将会从缓存区读取下一个字符，导致你输入的下一个字符实际上成为了能否循环的条件

**Comment by victoryban** [comment]
改进方法
1*要么用你后面的方法，用x代替getchar
2*要么你每次输入一个字符打个空格

**Comment by XiaoBaiBZS** [comment]
> 因为gtechar在判断是否进行下次循环时，将会从缓存区读取下一个字符，导致你输入的下一个字符实际上成为了能否循环的条件

感谢。

**Comment by sq4250** [comment]
拓展应用:可以用单行 ` while(getchar()!='\n'); ` 来清除输入缓冲区内容.
